name: alsf-rrp
channels:
  - conda-forge
  - bioconda
dependencies:
  - fastp=0.24.0=hee05c9d_1
  - isa-l=2.31.1=h5505292_1
  - libcxx=20.1.2=ha82da77_0
  - libdeflate=1.22=hd74edd7_0
prefix: /Users/hbeale/miniforge3/envs/alsf-rrp
